[project]
name = "transform_armor"
description = "Manipulate transform data for 'Transform Armor' Skyrim mod"
version = "0.0.1"
authors = [ {name = "Maid V.", email = "maid.v@protonmail.com" } ]
dependencies = [ "pyqt5" ]
